#include "Config.hpp"
#include <unordered_map>

#define _PUSH_FLAG_PROPERTY(x) {(#x), (x)}

namespace maxisoft::sandbox::config
{

FlagParser<DWORD> job_object_uilimit(
        {
            _PUSH_FLAG_PROPERTY(JOB_OBJECT_UILIMIT_HANDLES),
            _PUSH_FLAG_PROPERTY(JOB_OBJECT_UILIMIT_READCLIPBOARD),
            _PUSH_FLAG_PROPERTY(JOB_OBJECT_UILIMIT_WRITECLIPBOARD),
            _PUSH_FLAG_PROPERTY(JOB_OBJECT_UILIMIT_SYSTEMPARAMETERS),
            _PUSH_FLAG_PROPERTY(JOB_OBJECT_UILIMIT_DISPLAYSETTINGS),
            _PUSH_FLAG_PROPERTY(JOB_OBJECT_UILIMIT_GLOBALATOMS),
            _PUSH_FLAG_PROPERTY(JOB_OBJECT_UILIMIT_DESKTOP),
            _PUSH_FLAG_PROPERTY(JOB_OBJECT_UILIMIT_EXITWINDOWS)
        },
        "JOB_OBJECT_UILIMIT_");


FlagParser<std::string> integrity_flags(
        {
            {"Untrusted", "S-1-16-0"},
            {"low",       "S-1-16-4096"},
            {"Medium",    "S-1-16-8192"},
            {"high",      "S-1-16-12288"},
            {"System",    "S-1-16-16384"},
            {"Protected", "S-1-16-20480"},
            {"Secure",    "S-1-16-28672"}
        },
        ""
);

#define _PUSH_SE_FLAG_PROPERTY(x) {(#x), (x)}
static_assert(sizeof(decltype(TEXT("A")[0])) == sizeof(wchar_t));

FlagParser<std::string> se_privileges(
    {
//Temporary replace TEXT macro
#pragma push_macro("TEXT")
#undef TEXT
#define TEXT(x) (x)
_PUSH_SE_FLAG_PROPERTY(SE_CREATE_TOKEN_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_ASSIGNPRIMARYTOKEN_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_LOCK_MEMORY_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_INCREASE_QUOTA_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_UNSOLICITED_INPUT_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_MACHINE_ACCOUNT_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_TCB_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_SECURITY_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_TAKE_OWNERSHIP_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_LOAD_DRIVER_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_SYSTEM_PROFILE_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_SYSTEMTIME_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_PROF_SINGLE_PROCESS_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_INC_BASE_PRIORITY_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_CREATE_PAGEFILE_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_CREATE_PERMANENT_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_BACKUP_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_RESTORE_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_SHUTDOWN_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_DEBUG_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_AUDIT_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_SYSTEM_ENVIRONMENT_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_CHANGE_NOTIFY_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_REMOTE_SHUTDOWN_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_UNDOCK_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_SYNC_AGENT_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_ENABLE_DELEGATION_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_MANAGE_VOLUME_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_IMPERSONATE_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_CREATE_GLOBAL_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_TRUSTED_CREDMAN_ACCESS_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_RELABEL_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_INC_WORKING_SET_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_TIME_ZONE_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_CREATE_SYMBOLIC_LINK_NAME),
_PUSH_SE_FLAG_PROPERTY(SE_DELEGATE_SESSION_USER_IMPERSONATE_NAME)
    },
    "SE_"
#pragma pop_macro("TEXT")
);

FlagParser<DWORD64> proc_crea_policy_flags(
        {
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_DEP_ENABLE),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_DEP_ATL_THUNK_ENABLE),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_SEHOP_ENABLE),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_ON_REQ_RELOCS),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_RESERVED),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_RESERVED),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_RESERVED),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_RESERVED),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_RESERVED),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_RESERVED),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_ON_ALLOW_OPT_OUT),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_EXPORT_SUPPRESSION),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALLOW_STORE),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_AUDIT_NONSYSTEM_FONTS),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_RESERVED),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_RESERVED),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_MASK),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_DEFER),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_ALWAYS_ON),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_ALWAYS_OFF),
_PUSH_FLAG_PROPERTY(PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_RESERVED),
        },
        "PROCESS_CREATION_MITIGATION_POLICY_"
);
static_assert(sizeof(decltype(TEXT("A")[0])) == sizeof(wchar_t));
}
